name: Deploy

on:
  workflow_run:
    workflows:
      - Laravel Pint
    types:
      - completed
  release:
    type:
      - published

jobs:

  deploy:
    
    runs-on: ubuntu-latest 

    environment: ${{github.event_name=='workflow_run' && 'staging' || 'production'}}

  steps:
    - name: Deploy to forge
      env:
        DEPLOY_URL: ${{vars.DEPLOY_URL}}
      run: curl $DEPLOY_URL