name: Laravel Pint

on:
  push:
    branches:
      - main

jobs:
  laravel-pint:
    runs-on: ubuntu-latest


    steps:
     - name: Checkout Code
       uses: actions/github-script@v7.0.1
       with:
        ref: ${{ github.head_ref }}

     - name: Setup PHP and Composer
       uses: shivammathur/setup-php@v2
       with:
        php-version: '8.4'
        tools: composer:v2

     - name: Install Laravel Pint
       run: composer global require laravel/pint

     - name: Run Pint
       run: pint

     - name: Push Change Back to Repo
       run: |
        git config user.name "gh-actions"
        git config user.email "gh@laracast.com"
        git add .
        git commit -m "Laravel Pint" || exit 0
        git push